### ISSUE TITLE
Add AssertNothrow

### ISSUE THREAD

**Issue by nabijaczleweli** [banditcpp/snowhouse#13]
According to [Readme](https://github.com/joakimkarlsson/snowhouse#exceptions) support for checking if the code `throw`s is already there, but checking if the code _didn't_ throw is also very useful, so [here](https://github.com/nabijaczleweli/libYAML-wrapper/blob/master/test/testutil/throw.hpp#L28-L42)'s how I resolved it.
However, having that functionality built-in would be very nice as well.

**Comment by nabijaczleweli** [comment]
Any updates on this?

**Comment by joakimkarlsson** [comment]
I'm not sure I see the use for this. If code under test throws an unexpected exception, that's automatically a failed test. 

Why do we need a specific assert for this?

**Comment by nabijaczleweli** [comment]
First of all, as we all know, explicit is better than implicit, but this also expresses intent much better.

**Comment by sbeyer** [comment]
Adding my 2 cents to this 4 year old issue: I also don't see a use for this. One usually tests for specific behavior (including exception handling) of a class or method, not the absence of behavior. Yes, explicit is better than implicit, but I do not see a point in saying "I want to explicitly state that no exception is thrown". I am closing this issue now.
