### ISSUE TITLE
It is not aways possible to overide the operator << to get printing.

### ISSUE THREAD

**Issue by bogado** [banditcpp/snowhouse#20]
Sometimes there's a need to print an object on a different manner than the one used by default. Or you may need more detailed information on the output than you need on you usual operator <<. I would add a secondary way of teaching snowhouse how to print custom classes.

**Comment by sbeyer** [comment]
Hi @bogado, I think your problem can be solved using Stringizers (see, for example, stringize_test.cpp, `WithoutStreamOperatorButWithStringizer`).

**Comment by bogado** [comment]
Yes, I  eventually found it, maybe this should be on the docs to make it easily found.

Apart from that you can close the issue.

Victor

On November 26, 2016 9:14:16 AM PST, Stephan Beyer <notifications@github.com> wrote:
>Hi @bogado, I think your problem can be solved using Stringizers (see,
>for example, stringize_test.cpp,
>`WithoutStreamOperatorButWithStringizer`).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/banditcpp/snowhouse/issues/20#issuecomment-263074723

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
