### ISSUE TITLE
Output QString upon error

### ISSUE THREAD

**Issue by MartinDelille** [banditcpp/snowhouse#37]
I was using bandit v2.0.0 which was refering snowhouse v2.1.0.

I decided to move to the lastest version of bandit to fix a problem (combining multiple --skip), but I'm facing a problem.

```
/path/to/bandit/bandit/assertion_frameworks/snowhouse/stringize.h:53:56: error: use of overloaded operator '<<' is ambiguous (with operand types 'ostream' (aka 'basic_ostream<char>') and 'const QChar')
      static const bool value = sizeof(check(std::cout << x)) == sizeof(yes);
                                             ~~~~~~~~~ ^  ~
```

In fact I have redefined the following operator:

```
std::ostream& operator<<(std::ostream& stream, const QString& qstr);
```

If I remove this code, it compiles ok but the snowhouse output isn't explicit anymore when I come upon errors in my tests:

```
.
.......F...
There were failures!

settings_test handles_string:
/path/to/my/spec.cpp:111: Expected: equal to aaaaaaa
Actual: [ [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type], [unsupported type] ]

Test run complete. 12 tests run. 11 succeeded. 1 failed.
```

I managed to find a way to fix this but it is not totally satisfacting. Instead of defining:

```
std::ostream& operator<<(std::ostream& stream, const QString& qstr);
```

I defined:

```
std::ostream& operator<<(std::ostream& stream, const QChar& c);
```

And I have the following output in case of error:

```
.
.......F...
There were failures!

settings_test handles_string:
/path/to/my/spec.cpp:111: Expected: equal to aaaaaaa
Actual: [ b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b, b ]

Test run complete. 12 tests run. 11 succeeded. 1 failed.
```

Any idea to get a cleaner output display?

**Comment by sbeyer** [comment]
> In fact I have redefined the following operator:
> ```std::ostream& operator<<(std::ostream& stream, const QString& qstr);```

Have you redefined the operator only for your tests or is that redefinition done in your application anyways?

> Any idea to get a cleaner output display?

If you do not need your redefinition in general but only for the tests, you can implement a Stringizer. [Look it up in the snowhouse documentation](https://github.com/banditcpp/snowhouse#getting-better-output-for-your-types), it's easy.

In any way, I'd be interested in a minimal example for me to fix the bug (if there is one).

**Comment by MartinDelille** [comment]
It works like a charm! Thank you for the quick reply :-)
