### ISSUE TITLE
String whitespace comparison

### ISSUE THREAD

**Issue by MartinDelille** [banditcpp/snowhouse#42]
When comparing two string with whitespace, tab or carriage return, it is sometime difficult to understand what are the differences:

```
 (*) import summary:
file://path/to/spec.cpp:1035: Expected: equal to Summary

Actual: Summary

```

It would be nice to have a better whitespace display, like for example adding quote to expected and actual string.

Another usefull feature would be to have expected and actual string aligned.

See an output example below:

```
 (*) import summary:
file://path/to/spec.cpp:1035:
Expected equal to: "Summary
"
           Actual: "Summary
    "
```

This example show clearly that the actual string has 4 additional spaces.

**Comment by MartinDelille** [comment]
Hi @sbeyer !

First of all I wanted to wish you an amazing 2020 decade! ;-)

Thank you for implementing this feature!

I wondered if it is possible to use this feature or at least test it with bandit. I made a test project and since the current master ref is from june 2019 which doesn't include this feature yet.

Shall I checkout another bandit branch? or just update the snowhouse submodule ref to the latest version?

**Comment by sbeyer** [comment]
> I wondered if it is possible to use this feature or at least test it with bandit. I made a test project and since the current master ref is from june 2019 which doesn't include this feature yet.
> 
> Shall I checkout another bandit branch? or just update the snowhouse submodule ref to the latest version?

I wanted to release Snowhouse 5.0.0 before I update the submodule, but since there is demand: it's in master now :)

**Comment by MartinDelille** [comment]
It's working! Thanks again @sbeyer !

**Comment by MartinDelille** [comment]
I notice that only the first string is surrounded by quote:

```
import summary:
/path/to/my/spec.cpp:123: Expected: equal to: "Summary
"
           Actual: Summary
    
```

I guess this is due to the fact that my assertion test a QString.

I added the following code to stringize the QString (following your advice a couple of years ago):

```cpp
namespace snowhouse {
template <> struct Stringizer<QString> {
	static std::string ToString(const QString &s) {
		return s.toStdString();
	}
};
}
```
