### ISSUE TITLE
Show more information if AssertThrows fails

### ISSUE THREAD

**Issue by Cogitri** [banditcpp/snowhouse#47]
Hello,

it'd be nice if AssertThrows showed more information if it failed instead of just saying that it didn't get the exception it wanted. Maybe it'd be possible to test if the exception can be gotten via std::current_exception and if so get the description of that? I'd like to implement that if you're OK with that.

**Comment by sbeyer** [comment]
I would be interested in how to achieve that, so, sure, go for it :+1:

Note that you can base your feature branch on the [prepare-v5.0.0](https://github.com/banditcpp/snowhouse/tree/prepare-v5.0.0) branch that defaults to C++11 (which makes it easier to use `std::current_exception`).

**Comment by Cogitri** [comment]
Thanks, gonna do that :)
