### ISSUE TITLE
How can I test a vector?

### ISSUE THREAD

**Issue by MartinDelille** [banditcpp/snowhouse#51]
I found Snowhouse pretty useful to test some simple vector:

```cpp
AssertThat(myVector, Is().OfLength(1).Containing(4));
```

But if I can't find a way to check my vector is equal to `{2, 5}`.

The following assertion works for `{2, 5}` and `{5, 2}`:
```cpp
AssertThat(myVector, Is().OfLength(Of1).Containing(2).Containing(5));
```

**Comment by sbeyer** [comment]
> But if I can't find a way to check my vector is equal to `{2, 5}`.

It's just like you said:
```c++
  AssertThat(myVector, Is().EqualTo(std::vector<int>{2, 5});
  AssertThat(myVector, Equals(std::vector<int>{2, 5});
```
and there is a container-oblivious version, e.g., check if the content of a list is equal to the content of a vector:
```c++
  AssertThat(myList, Is().EqualToContainer(std::vector<int>{2,5}));
  AssertThat(myList, EqualsContainer(std::vector<int>{2,5}));
```

But, yes, it would be nice to use some C++11-features here and be able to simply write `{2,5}` instead of `std::vector<int>{2, 5}`.

**Comment by MartinDelille** [comment]
It works if I specify the type (which is `QVector<short>` in my case)
